# Generated by Django 2.1.7 on 2019-09-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
