# Generated by Django 2.2 on 2019-09-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190910_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginPage',
        ),
    ]
